services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always
    deploy:
      replicas: 3
  submitter:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: python src/submit_jobs.py