services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/app/src
    restart: always
    deploy:
      replicas: 3
  submitter:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/app/src
    command: python src/scripts/submit_jobs.py
  monitor:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/app/src
    restart: always
    command: python src/scripts/monitor.py