services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/app/src
    restart: always
    deploy:
      replicas: 3
  monitor:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/app/src
    restart: always
    command: python src/scripts/monitor.py
  api:
    build: .
    depends_on:
      - redis
    environment:
    - REDIS_HOST=redis
    - PYTHONPATH=/app/src
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"